platform :ios, '14.0'

# CocoaPods analytics sends network stats, disable if you wish.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

source 'https://github.com/CocoaPods/Specs.git'

project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pods
  flutter_application_path = '../'
  load File.join(flutter_application_path, 'ios', 'Flutter', 'podhelper.rb')

  # Firebase dependencies
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  # Google Maps dependency
  pod 'GoogleMaps'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
